# Generated by Django 4.1 on 2026-01-06 17:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_user_username"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
